# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: "idka"
  brokers: "kafka04-prod01.messagehub.services.us-south.bluemix.net:9093,kafka04-prod02.messagehub.services.us-south.bluemix.net:9093,kafka04-prod03.messagehub.services.us-south.bluemix.net:9093,kafka04-prod04.messagehub.services.us-south.bluemix.net:9093,kafka04-prod05.messagehub.services.us-south.bluemix.net:9093"
  topic: "dubee"
  net:
    sasl:
      enable: true
      user: "K1jzCQSVE6u54zUs"
      password: "59X5zdlx4x1MP0BI1PDT6EPD5uylvphe"
    tls:
      enable: true
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: kafka-message-logger-2
